#!/bin/bash
erl -name node1@127.0.0.1 -detached -pa ./proc_server/_build/default/lib/proc_server/ebin -eval "application:load(proc_server), application:start(proc_server)" #-connect_all false

for i in {2..3}
do
   # start new node and connect to previsou node
   erl -name "node$i@127.0.0.1" -pa ./proc_server/_build/default/lib/proc_server/ebin -eval "net_kernel:connect('node$(($i-1))@127.0.0.1'), application:load(proc_server), application:start(proc_server)" -detached
   #erl -name "node$i@127.0.0.1" -detached
   sleep 0.5
done


#	erl -name node2@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node3@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node4@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node5@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node6@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node7@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
#       erl -name node8@127.0.0.1 -eval "net_adm:ping('node1@127.0.0.1')" -detached
